# .github/bump.yml
---
release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
branch:
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
categories:
  - title: 'Changes'
    commits:
      - ''
bump:
  default: 'patch'
files:
  - file-path: 'VERSION'
    line: 1
  - file-path: 'version.sh'
    line: 1
