# .github/bump.yml
---
release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
categories:
  - title: 'Changes'
    commits:
      - ''
files:
  - file-path: 'VERSION'
    line: 1
  - file-path: 'version.sh'
    line: 1

