name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Which version part to bump?
        required: true
        options:
          - major
          - minor
          - patch
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: Run tests
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: pip install bump-my-version
      - run: bump-my-version bump ${{ inputs.version }} -vv
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

