name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Which version part to bump?
        required: true
        options:
          - major
          - minor
          - patch
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/checkout@master
      - name: debug
        run: |
          echo ${{ github.ref }}
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: Run tests
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Conventional Changelog Action
        id: conventional-changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          release-count: '0'
          skip-version-file: 'true'
          git-branch: 'my-maintenance-branch'
      - name: Bump version
        run: sed -i 's/VERSION=.*/VERSION=${{ steps.conventional-changelog.version }}/' VERSION

